Homework3
egorzainullin/FSharp pull request #3
Opened 2018-03-07 15:40 UTC by egorzainullin

2018-03-30 07:42 UTC, yurii-litvinov requested changes
Как-то очень мало тестов, тестируется только базовая функциональность. Пусть арифметическое дерево будет зачтено (там хоть деление на 0 проверили), а к остальынм задачам надо больше тестов --- на граничный и, если возможно, некорректный ввод.

2018-03-30 07:42 UTC, yurii-litvinov commented on Homework3/Homework3/Program.fs
> +                    else -1
option?

2018-03-30 07:42 UTC, yurii-litvinov commented on Homework3/Homework3/Program.fs
> +        let countEven3 list =
Не очень информативные имена функций

2018-03-31 13:38 UTC, yurii-litvinov requested changes
Дерево доисправляйте, пожалуйста. Остальные зачтены

2018-03-31 13:38 UTC, yurii-litvinov commented on Homework3/Homework3/Tree.fs
> +        | NullTree
Ой, всё ж хорошо было. Теперь возможны конструкции вида `Tree(1, NullTree, NullTree)` и `Tip 1`, означающие, наверное, одно и то же, но с точки зрения оператора сравнения не равные.

2018-03-31 13:58 UTC, egorzainullin commented on Homework3/Homework3/Tree.fs
> +        | NullTree
я вернул как было, но тут некоторые деревья не записываются, вроде пустого, вырожденного в список, разве нет?

2018-03-31 14:02 UTC, yurii-litvinov commented on Homework3/Homework3/Tree.fs
> +        | NullTree
Ага. Если такие деревья хочется, можно Tip убрать.

2018-03-31 19:48 UTC, merged